version: "3"
services:
  test:
    image: "sminch/tunnel-check:0.1.1"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "python3 -s /workdir/run.py"
    network_mode: host
    volumes: 
      - ./py_files/:/workdir/

  sauce-connect:
    image: "saucelabs/sauce-connect:5.0"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "run -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -c /opt/sauce-connect.yaml"
    network_mode: host
    volumes: 
      - ./sauce-connect.yaml:/opt/sauce-connect.yaml
