apiVersion: v1alpha
kind: imagerunner
sauce:
  region: us-west-1
suites:
  - name: Check Tunnel Status SO Edition
    workload: webdriver
    #resourceProfile: c6m6
    image: sminch/tunnel-check:0.2.2
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    # the command to run your tests
    entrypoint: "python3 -s run.py"
    artifacts:
      - "/workdir/file.log"
services:
  - name: Sauce Connect
    workload: webdriver
    image: "saucelabs/sauce-connect:5.0"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    entrypoint: "run -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -c sauce-connect.yaml"

artifacts:
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts
